# name: Build and Deploy
# on:
#   push:
#     branches:
#       - develop
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 🛎️
#         uses: actions/checkout@v2.3.1

#       - name: Install dependency and deploy
#         run: |
#           npm ci
#           npm run-script deploy
